// The seeded product catalogue.
//
// Every entry points at photos that live in the frontend's public folder
// (frontend/public/images/products/<slug>/), so the storefront never depends
// on a third-party CDN staying up — the old seed used remote URLs and roughly
// half of them had gone dead, leaving grey placeholders on the shop.
//
// Each product carries its own specs, highlights and attributes; nothing is
// shared boilerplate, so the product pages read like a real catalogue.

import productMedia from "./generated/productMedia.js";

// The photos for a product folder.
//
// Which photos exist, what sizes they come in and which variant each one
// depicts all live in the generated manifest, written by the media scripts from
// what is actually on disk. Nothing here is hand-typed, so the catalogue and
// the filesystem cannot drift apart.
const imgs = (slug) => {
  const entries = productMedia[slug] || [];

  return entries.map((entry) => ({
    url: entry.url,
    attributes: entry.attributes || {},
    width: entry.width,
    height: entry.height,
    srcset: entry.srcset,
    srcsetAvif: entry.srcsetAvif,
  }));
};

export const catalogue = [
  // ── Smartphones ──────────────────────────────────────────────
  {
    name: "Apple iPhone 13 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 89900,
    mrp: 109900,
    countInStock: 34,
    isFeatured: true,
    images: imgs("iphone-13-pro"),
    description:
      "iPhone 13 Pro pairs the A15 Bionic chip with a 120Hz Super Retina XDR ProMotion display and a pro camera system that shoots ProRes video. The surgical-grade stainless steel frame and Ceramic Shield front make it as tough as it is fast.",
    benefits: [
      "Free delivery by tomorrow in metro cities",
      "1 year Apple India warranty with doorstep service",
      "No Cost EMI from ₹7,491/month on leading banks",
      "7-day replacement if the device is dead on arrival",
    ],
    attributes: { Color: "Sierra Blue", Storage: "128 GB", RAM: "6 GB", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Display: "6.1-inch Super Retina XDR OLED, 120Hz ProMotion",
      Resolution: "2532 x 1170 pixels at 460 ppi",
      Processor: "A15 Bionic, 6-core CPU",
      RAM: "6 GB",
      Storage: "128 GB",
      "Rear Camera": "12MP Wide + 12MP Ultra Wide + 12MP Telephoto",
      "Front Camera": "12MP TrueDepth",
      Battery: "3095 mAh, up to 22 hours video playback",
      Charging: "20W fast charge, MagSafe 15W wireless",
      "Water Resistance": "IP68 (6 m for 30 minutes)",
      OS: "iOS 15, upgradable",
      "In the Box": "iPhone, USB-C to Lightning cable, documentation",
    },
  },
  {
    name: "Apple iPhone X",
    brand: "Apple",
    category: "Smartphones",
    price: 34999,
    mrp: 45999,
    countInStock: 21,
    isFeatured: false,
    images: imgs("iphone-x"),
    description:
      "The iPhone that introduced Face ID and the edge-to-edge Super Retina display. A11 Bionic still handles everyday apps comfortably, and the dual 12MP cameras with Portrait Lighting remain excellent for the price.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months seller warranty",
      "7-day easy returns",
      "Certified pre-owned, fully tested by NexaMart",
    ],
    attributes: { Color: "Space Grey", Storage: "64 GB", RAM: "3 GB", Warranty: "6 Months Seller Warranty" },
    specs: {
      Display: "5.8-inch Super Retina OLED",
      Resolution: "2436 x 1125 pixels at 458 ppi",
      Processor: "A11 Bionic, 6-core CPU",
      RAM: "3 GB",
      Storage: "64 GB",
      "Rear Camera": "12MP Wide + 12MP Telephoto, OIS",
      "Front Camera": "7MP TrueDepth with Face ID",
      Battery: "2716 mAh",
      Charging: "Fast charge, Qi wireless",
      "Water Resistance": "IP67",
      OS: "iOS 11, upgradable to iOS 16",
      "In the Box": "iPhone, Lightning cable, EarPods",
    },
  },
  {
    name: "Samsung Galaxy S10",
    brand: "Samsung",
    category: "Smartphones",
    price: 38999,
    mrp: 55900,
    countInStock: 40,
    isFeatured: true,
    images: imgs("samsung-galaxy-s10"),
    description:
      "Galaxy S10 packs a Dynamic AMOLED display with HDR10+ into a slim glass-and-metal body. The triple rear camera covers ultra-wide, wide and telephoto, and the in-display ultrasonic fingerprint sensor still feels premium today.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Samsung India warranty",
      "Exchange offer up to ₹8,000 on your old phone",
      "7-day easy returns",
    ],
    attributes: { Color: "Prism White", Storage: "128 GB", RAM: "8 GB", Warranty: "1 Year Samsung India Warranty" },
    specs: {
      Display: "6.1-inch Dynamic AMOLED, HDR10+",
      Resolution: "3040 x 1440 pixels (QHD+)",
      Processor: "Exynos 9820, Octa-core",
      RAM: "8 GB",
      Storage: "128 GB, expandable via microSD",
      "Rear Camera": "12MP Wide + 12MP Telephoto + 16MP Ultra Wide",
      "Front Camera": "10MP",
      Battery: "3400 mAh",
      Charging: "15W fast charge, Wireless PowerShare",
      "Water Resistance": "IP68",
      OS: "Android 9, upgradable to Android 12",
      "In the Box": "Handset, charger, AKG earphones, cable",
    },
  },
  {
    name: "Samsung Galaxy S8",
    brand: "Samsung",
    category: "Smartphones",
    price: 21999,
    mrp: 32999,
    countInStock: 26,
    isFeatured: false,
    images: imgs("samsung-galaxy-s8"),
    description:
      "The Galaxy S8's Infinity Display curved the screen around the edges and set the template every phone followed. A dependable single 12MP dual-pixel camera, wireless charging and IP68 protection make it a solid budget pick.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months seller warranty",
      "7-day easy returns",
      "100% secure payment",
    ],
    attributes: { Color: "Midnight Black", Storage: "64 GB", RAM: "4 GB", Warranty: "6 Months Seller Warranty" },
    specs: {
      Display: "5.8-inch Quad HD+ Super AMOLED Infinity Display",
      Resolution: "2960 x 1440 pixels",
      Processor: "Exynos 8895, Octa-core",
      RAM: "4 GB",
      Storage: "64 GB, expandable up to 256 GB",
      "Rear Camera": "12MP Dual Pixel, f/1.7, OIS",
      "Front Camera": "8MP autofocus",
      Battery: "3000 mAh",
      Charging: "Adaptive fast charging, Qi wireless",
      "Water Resistance": "IP68",
      OS: "Android 7, upgradable to Android 9",
      "In the Box": "Handset, charger, AKG earphones, cable",
    },
  },
  {
    name: "OPPO F19 Pro+ 5G",
    brand: "OPPO",
    category: "Smartphones",
    price: 22990,
    mrp: 25990,
    countInStock: 52,
    isFeatured: true,
    images: imgs("oppo-f19-pro-plus"),
    description:
      "F19 Pro+ brings 50W flash charge and a 48MP AI quad camera to the mid-range. The 7.8 mm body weighs just 173 g, and the Dimensity 800U keeps 5G browsing and gaming smooth all day.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year OPPO India warranty + 6 months on accessories",
      "No Cost EMI from ₹3,832/month",
      "7-day easy returns",
    ],
    attributes: { Color: "Fluid Black", Storage: "128 GB", RAM: "8 GB", Warranty: "1 Year OPPO India Warranty" },
    specs: {
      Display: "6.43-inch AMOLED, 90Hz",
      Resolution: "2400 x 1080 pixels",
      Processor: "MediaTek Dimensity 800U 5G",
      RAM: "8 GB",
      Storage: "128 GB",
      "Rear Camera": "48MP Main + 8MP Ultra Wide + 2MP Macro + 2MP Mono",
      "Front Camera": "16MP",
      Battery: "4310 mAh",
      Charging: "50W Flash Charge (0-100% in 48 min)",
      Network: "Dual 5G SIM",
      OS: "ColorOS 11.1 on Android 11",
      "In the Box": "Handset, 50W charger, case, cable",
    },
  },
  {
    name: "OPPO K1",
    brand: "OPPO",
    category: "Smartphones",
    price: 13990,
    mrp: 16990,
    countInStock: 63,
    isFeatured: false,
    images: imgs("oppo-k1"),
    description:
      "K1 was the first phone in its class with an in-display fingerprint reader. The waterdrop AMOLED screen and 25MP AI selfie camera make it a strong everyday phone for students and first-time buyers.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year OPPO India warranty",
      "Pay on delivery available",
      "7-day easy returns",
    ],
    attributes: { Color: "Astral Blue", Storage: "64 GB", RAM: "4 GB", Warranty: "1 Year OPPO India Warranty" },
    specs: {
      Display: "6.4-inch Waterdrop AMOLED",
      Resolution: "2340 x 1080 pixels",
      Processor: "Snapdragon 660 AIE",
      RAM: "4 GB",
      Storage: "64 GB, expandable via microSD",
      "Rear Camera": "16MP + 2MP depth sensor",
      "Front Camera": "25MP AI Beautification",
      Battery: "3600 mAh",
      Security: "In-display fingerprint sensor",
      Charging: "10W",
      OS: "ColorOS 5.2 on Android 8.1",
      "In the Box": "Handset, charger, case, cable, SIM tool",
    },
  },
  {
    name: "Realme XT",
    brand: "Realme",
    category: "Smartphones",
    price: 15999,
    mrp: 18999,
    countInStock: 48,
    isFeatured: false,
    images: imgs("realme-xt"),
    description:
      "Realme XT was India's first 64MP quad-camera phone. The Super AMOLED display, VOOC 3.0 fast charging and hybrid SIM slot still make it a value-heavy pick in the budget segment.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Realme India warranty",
      "No Cost EMI from ₹2,666/month",
      "7-day easy returns",
    ],
    attributes: { Color: "Pearl Blue", Storage: "128 GB", RAM: "8 GB", Warranty: "1 Year Realme India Warranty" },
    specs: {
      Display: "6.4-inch Super AMOLED",
      Resolution: "2340 x 1080 pixels",
      Processor: "Snapdragon 712 AIE",
      RAM: "8 GB",
      Storage: "128 GB, expandable via microSD",
      "Rear Camera": "64MP + 8MP Ultra Wide + 2MP Macro + 2MP Portrait",
      "Front Camera": "16MP Sony IMX471",
      Battery: "4000 mAh",
      Charging: "VOOC Flash Charge 3.0 (20W)",
      Security: "In-display fingerprint sensor",
      OS: "ColorOS 6 on Android 9",
      "In the Box": "Handset, 20W VOOC charger, case, cable",
    },
  },
  {
    name: "Vivo X21",
    brand: "Vivo",
    category: "Smartphones",
    price: 17990,
    mrp: 23990,
    countInStock: 30,
    isFeatured: false,
    images: imgs("vivo-x21"),
    description:
      "X21 combines a 6.28-inch FullView AMOLED panel with an under-display fingerprint scanner and dual rear cameras tuned for low light. The AI Face Access unlocks in around 0.1 seconds.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months seller warranty",
      "Pay on delivery available",
      "7-day easy returns",
    ],
    attributes: { Color: "Ruby Red", Storage: "128 GB", RAM: "6 GB", Warranty: "6 Months Seller Warranty" },
    specs: {
      Display: "6.28-inch FullView AMOLED",
      Resolution: "2280 x 1080 pixels",
      Processor: "Snapdragon 660 AIE",
      RAM: "6 GB",
      Storage: "128 GB",
      "Rear Camera": "12MP Dual Pixel + 5MP depth",
      "Front Camera": "12MP with AI Face Beauty",
      Battery: "3200 mAh",
      Security: "Under-display fingerprint, AI Face Access",
      Charging: "Dual-Engine fast charging",
      OS: "Funtouch OS 4.0 on Android 8.1",
      "In the Box": "Handset, charger, case, cable, earphones",
    },
  },

  // ── Laptops ──────────────────────────────────────────────────
  {
    name: 'Apple MacBook Pro 14" Space Grey',
    brand: "Apple",
    category: "Laptops",
    price: 169900,
    mrp: 194900,
    countInStock: 18,
    isFeatured: true,
    images: imgs("apple-macbook-pro-14-inch-space-grey"),
    description:
      "The 14-inch MacBook Pro puts a Liquid Retina XDR display, a full complement of ports and all-day battery life into a machine that stays silent under load. Built for developers, editors and anyone who runs heavy tools on battery.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Apple India warranty, extendable with AppleCare+",
      "No Cost EMI from ₹14,158/month",
      "Free setup assistance from NexaMart specialists",
    ],
    attributes: { Color: "Space Grey", Storage: "512 GB SSD", RAM: "16 GB", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Display: "14.2-inch Liquid Retina XDR, 120Hz ProMotion",
      Resolution: "3024 x 1964 at 254 ppi, 1000 nits sustained",
      Processor: "Apple M-series, 10-core CPU / 16-core GPU",
      RAM: "16 GB unified memory",
      Storage: "512 GB SSD",
      Battery: "70Wh, up to 17 hours wireless web",
      Ports: "3x Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5 mm",
      Keyboard: "Backlit Magic Keyboard with Touch ID",
      Audio: "Six-speaker system with force-cancelling woofers",
      Webcam: "1080p FaceTime HD",
      Weight: "1.6 kg",
      OS: "macOS",
    },
  },
  {
    name: "ASUS Zenbook Pro Duo",
    brand: "ASUS",
    category: "Laptops",
    price: 149990,
    mrp: 179990,
    countInStock: 12,
    isFeatured: true,
    images: imgs("asus-zenbook-pro-dual-screen-laptop"),
    description:
      "A genuine dual-screen laptop: a 4K OLED main display plus the ScreenPad Plus secondary panel above the keyboard. Timeline, reference docs or chat live on the second screen while you work full-screen on the first.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year ASUS onsite warranty",
      "No Cost EMI from ₹12,499/month",
      "7-day replacement on manufacturing defects",
    ],
    attributes: { Color: "Celestial Blue", Storage: "1 TB SSD", RAM: "16 GB", Warranty: "1 Year ASUS Onsite Warranty" },
    specs: {
      Display: "15.6-inch 4K OLED touchscreen",
      "Secondary Display": "14-inch ScreenPad Plus 4K touchscreen",
      Processor: "Intel Core i7, 8-core",
      RAM: "16 GB DDR4",
      Storage: "1 TB PCIe NVMe SSD",
      Graphics: "NVIDIA GeForce RTX, 6 GB GDDR6",
      Battery: "92Wh",
      Ports: "2x Thunderbolt 4, USB 3.2 Type-A, HDMI 2.1",
      Keyboard: "Backlit chiclet with ErgoLift hinge",
      Audio: "Harman Kardon certified stereo",
      Weight: "2.3 kg",
      OS: "Windows 11 Home",
    },
  },
  {
    name: "Huawei MateBook X Pro",
    brand: "Huawei",
    category: "Laptops",
    price: 119990,
    mrp: 139990,
    countInStock: 15,
    isFeatured: false,
    images: imgs("huawei-matebook-x-pro"),
    description:
      "A 1.33 kg magnesium-alloy ultrabook built around a 3:2 touchscreen that shows noticeably more of a document or web page than a 16:9 panel. The pop-up camera keeps the bezels almost invisible.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Huawei warranty",
      "No Cost EMI from ₹9,999/month",
      "7-day easy returns",
    ],
    attributes: { Color: "Emerald Green", Storage: "1 TB SSD", RAM: "16 GB", Warranty: "1 Year Huawei Warranty" },
    specs: {
      Display: "14.2-inch 3:2 LTPS touchscreen",
      Resolution: "3120 x 2080, 90Hz, 500 nits",
      Processor: "Intel Core i7, 12-core",
      RAM: "16 GB LPDDR5",
      Storage: "1 TB NVMe SSD",
      Graphics: "Intel Iris Xe",
      Battery: "60Wh, 90W SuperCharge",
      Ports: "2x Thunderbolt 4, USB-C, 3.5 mm",
      Audio: "Six-speaker quad-channel sound",
      Webcam: "1080p pop-up camera",
      Weight: "1.33 kg",
      OS: "Windows 11 Home",
    },
  },
  {
    name: "Lenovo Yoga 920 2-in-1",
    brand: "Lenovo",
    category: "Laptops",
    price: 84990,
    mrp: 104990,
    countInStock: 20,
    isFeatured: false,
    images: imgs("lenovo-yoga-920"),
    description:
      "The watchband hinge folds a full 360 degrees, so the Yoga 920 works as a laptop, a tent for presentations or a tablet for note-taking with the included Active Pen.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Lenovo onsite warranty",
      "Active Pen included in the box",
      "7-day easy returns",
    ],
    attributes: { Color: "Platinum Silver", Storage: "512 GB SSD", RAM: "8 GB", Warranty: "1 Year Lenovo Onsite Warranty" },
    specs: {
      Display: "13.9-inch Full HD IPS touchscreen",
      Resolution: "1920 x 1080",
      Processor: "Intel Core i7, quad-core",
      RAM: "8 GB LPDDR3",
      Storage: "512 GB PCIe SSD",
      Graphics: "Intel UHD Graphics 620",
      Battery: "70Wh, up to 15 hours",
      Ports: "2x Thunderbolt 3, USB 3.0 Type-A, 3.5 mm",
      "Form Factor": "360-degree convertible with watchband hinge",
      Security: "Fingerprint reader",
      Weight: "1.37 kg",
      OS: "Windows 11 Home",
    },
  },
  {
    name: "Dell XPS 13 9300",
    brand: "Dell",
    category: "Laptops",
    price: 99990,
    mrp: 124990,
    countInStock: 24,
    isFeatured: true,
    images: imgs("new-dell-xps-13-9300-laptop"),
    description:
      "The XPS 13 shrinks a 13.4-inch InfinityEdge display into an 11-inch chassis. Machined aluminium outside, carbon fibre palm rest inside, and a 16:10 panel that gives you back vertical space for code and documents.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Dell Premium Support with onsite service",
      "No Cost EMI from ₹8,332/month",
      "7-day easy returns",
    ],
    attributes: { Color: "Frost White", Storage: "512 GB SSD", RAM: "16 GB", Warranty: "1 Year Dell Premium Support" },
    specs: {
      Display: "13.4-inch FHD+ InfinityEdge, 16:10",
      Resolution: "1920 x 1200, 500 nits",
      Processor: "Intel Core i7, quad-core",
      RAM: "16 GB LPDDR4x",
      Storage: "512 GB PCIe NVMe SSD",
      Graphics: "Intel Iris Plus",
      Battery: "52Wh, up to 12 hours",
      Ports: "2x Thunderbolt 3, microSD, 3.5 mm",
      Keyboard: "Backlit, larger keycaps",
      Security: "Fingerprint reader in power button, IR camera",
      Weight: "1.2 kg",
      OS: "Windows 11 Home",
    },
  },

  // ── Tablets ──────────────────────────────────────────────────
  {
    name: "Apple iPad Mini (2021) Starlight",
    brand: "Apple",
    category: "Tablets",
    price: 49900,
    mrp: 54900,
    countInStock: 29,
    isFeatured: true,
    images: imgs("ipad-mini-2021-starlight"),
    description:
      "The iPad mini fits a full 8.3-inch Liquid Retina display into something you can hold in one hand. USB-C charging, Touch ID in the top button and Apple Pencil 2 support make it the most portable serious tablet Apple sells.",
    benefits: [
      "Free delivery by tomorrow in metro cities",
      "1 year Apple India warranty",
      "No Cost EMI from ₹4,158/month",
      "Apple Pencil 2 compatible (sold separately)",
    ],
    attributes: { Color: "Starlight", Storage: "64 GB", RAM: "4 GB", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Display: "8.3-inch Liquid Retina, True Tone",
      Resolution: "2266 x 1488 at 326 ppi",
      Processor: "A15 Bionic, 6-core CPU",
      RAM: "4 GB",
      Storage: "64 GB",
      "Rear Camera": "12MP Wide with Smart HDR 4",
      "Front Camera": "12MP Ultra Wide with Centre Stage",
      Battery: "Up to 10 hours web browsing",
      Charging: "USB-C, 20W fast charge",
      Security: "Touch ID in top button",
      Connectivity: "Wi-Fi 6, optional 5G",
      Weight: "293 g",
    },
  },
  {
    name: "Samsung Galaxy Tab S8+ Grey",
    brand: "Samsung",
    category: "Tablets",
    price: 74999,
    mrp: 89999,
    countInStock: 22,
    isFeatured: true,
    images: imgs("samsung-galaxy-tab-s8-plus-grey"),
    description:
      "A 12.4-inch Super AMOLED tablet that ships with the S Pen in the box. DeX mode turns it into a desktop-style workspace, and the 10,090 mAh battery holds up through a full day of drawing or streaming.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Samsung India warranty",
      "S Pen included in the box",
      "No Cost EMI from ₹6,250/month",
    ],
    attributes: { Color: "Graphite Grey", Storage: "128 GB", RAM: "8 GB", Warranty: "1 Year Samsung India Warranty" },
    specs: {
      Display: "12.4-inch Super AMOLED, 120Hz",
      Resolution: "2800 x 1752",
      Processor: "Snapdragon 8 Gen 1",
      RAM: "8 GB",
      Storage: "128 GB, expandable via microSD",
      "Rear Camera": "13MP Wide + 6MP Ultra Wide",
      "Front Camera": "12MP Ultra Wide",
      Battery: "10,090 mAh",
      Charging: "45W Super Fast Charging",
      Stylus: "S Pen included, 2.8 ms latency",
      Audio: "Quad speakers tuned by AKG",
      OS: "One UI on Android, Samsung DeX support",
    },
  },
  {
    name: "Samsung Galaxy Tab A White",
    brand: "Samsung",
    category: "Tablets",
    price: 18999,
    mrp: 23999,
    countInStock: 45,
    isFeatured: false,
    images: imgs("samsung-galaxy-tab-white"),
    description:
      "A light everyday tablet for reading, video calls and streaming. Kids Mode, dual speakers and a battery that comfortably lasts a long flight make it the family tablet that gets left on the coffee table.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Samsung India warranty",
      "Pay on delivery available",
      "7-day easy returns",
    ],
    attributes: { Color: "Pearl White", Storage: "64 GB", RAM: "4 GB", Warranty: "1 Year Samsung India Warranty" },
    specs: {
      Display: "10.5-inch TFT LCD",
      Resolution: "1920 x 1200",
      Processor: "Octa-core, up to 2.0 GHz",
      RAM: "4 GB",
      Storage: "64 GB, expandable up to 1 TB",
      "Rear Camera": "8MP autofocus",
      "Front Camera": "5MP",
      Battery: "7040 mAh",
      Charging: "15W fast charging",
      Audio: "Dual speakers with Dolby Atmos",
      Connectivity: "Wi-Fi, optional LTE",
      Weight: "508 g",
    },
  },

  // ── Audio ────────────────────────────────────────────────────
  {
    name: "Apple AirPods (3rd Generation)",
    brand: "Apple",
    category: "Audio",
    price: 18900,
    mrp: 20900,
    countInStock: 68,
    isFeatured: true,
    images: imgs("apple-airpods"),
    description:
      "AirPods with Spatial Audio and Adaptive EQ tune the sound to the shape of your ear in real time. Sweat and water resistant, with a MagSafe charging case that takes the total listening time past 30 hours.",
    benefits: [
      "Free delivery by tomorrow in metro cities",
      "1 year Apple India warranty",
      "Instant pairing with iPhone, iPad and Mac",
      "7-day easy returns",
    ],
    attributes: { Color: "White", "Battery Life": "30 hours with case", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Type: "True wireless earbuds",
      Drivers: "Custom high-excursion Apple driver",
      "Audio Features": "Spatial Audio with dynamic head tracking, Adaptive EQ",
      Battery: "6 hours listening, 30 hours with case",
      Charging: "MagSafe, Qi wireless or Lightning",
      "Quick Charge": "5 minutes for 1 hour of listening",
      Controls: "Force sensor on the stem",
      "Water Resistance": "IPX4 (earbuds and case)",
      Chip: "Apple H1 headphone chip",
      Connectivity: "Bluetooth 5.0",
      "In the Box": "AirPods, MagSafe case, Lightning cable",
      Weight: "4.28 g per earbud",
    },
  },
  {
    name: "Apple AirPods Max Silver",
    brand: "Apple",
    category: "Audio",
    price: 59900,
    mrp: 64900,
    countInStock: 14,
    isFeatured: true,
    images: imgs("apple-airpods-max-silver"),
    description:
      "Over-ear headphones with a machined aluminium cup, a breathable knit-mesh canopy and computational audio driven by an H1 chip in each ear. Active Noise Cancellation here is genuinely class-leading.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Apple India warranty",
      "No Cost EMI from ₹4,991/month",
      "Smart Case included for low-power state",
    ],
    attributes: { Color: "Silver", "Battery Life": "20 hours with ANC", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Type: "Over-ear wireless headphones",
      Drivers: "40 mm Apple-designed dynamic driver",
      "Noise Control": "Active Noise Cancellation and Transparency mode",
      "Audio Features": "Spatial Audio, Adaptive EQ",
      Battery: "Up to 20 hours with ANC on",
      "Quick Charge": "5 minutes for 1.5 hours of listening",
      Charging: "Lightning",
      Controls: "Digital Crown and noise control button",
      Chip: "Apple H1 chip in each ear cup",
      Sensors: "Optical, position, case-detect, accelerometer",
      "In the Box": "AirPods Max, Smart Case, Lightning to USB-C cable",
      Weight: "384.8 g",
    },
  },
  {
    name: "Beats Flex Wireless Earphones",
    brand: "Beats",
    category: "Audio",
    price: 4999,
    mrp: 7900,
    countInStock: 92,
    isFeatured: false,
    images: imgs("beats-flex-wireless-earphones"),
    description:
      "Neckband earphones built for all-day wear. Magnetic earbuds pause playback the moment you clip them together, and the Apple W1 chip handles instant pairing and device switching.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Beats India warranty",
      "USB-C fast fuel charging",
      "7-day easy returns",
    ],
    attributes: { Color: "Beats Black", "Battery Life": "12 hours", Warranty: "1 Year Beats India Warranty" },
    specs: {
      Type: "Wireless neckband earphones",
      Drivers: "Dual-chamber acoustic design",
      Battery: "Up to 12 hours",
      "Quick Charge": "Fast Fuel — 10 minutes for 1.5 hours",
      Charging: "USB-C",
      Chip: "Apple W1 headphone chip",
      Controls: "Inline remote with mic and volume",
      Features: "Magnetic earbuds with auto play/pause",
      "Ear Tips": "Four sizes included",
      Connectivity: "Bluetooth, Class 1",
      "In the Box": "Earphones, four eartip sizes, USB-C cable",
      Weight: "18.6 g",
    },
  },
  {
    name: "Apple HomePod Mini Cosmic Grey",
    brand: "Apple",
    category: "Audio",
    price: 10900,
    mrp: 12900,
    countInStock: 37,
    isFeatured: false,
    images: imgs("apple-homepod-mini-cosmic-grey"),
    description:
      "A palm-sized smart speaker with 360-degree audio and a computational engine that tunes every note in real time. Pair two for stereo, or use it as a Siri hub for the rest of your home.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Apple India warranty",
      "Works as a HomeKit hub",
      "7-day easy returns",
    ],
    attributes: { Color: "Cosmic Grey", Power: "Mains powered", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Type: "Smart speaker",
      Audio: "Full-range driver with dual passive radiators",
      Sound: "360-degree audio with computational tuning",
      "Voice Assistant": "Siri with four-microphone array",
      Connectivity: "Wi-Fi, Bluetooth 5.0, Thread",
      "Smart Home": "HomeKit hub, Intercom",
      "Stereo Pair": "Supported with a second HomePod mini",
      Power: "USB-C with 20W adapter included",
      Dimensions: "84.3 mm high, 97.9 mm wide",
      Weight: "345 g",
      Display: "Backlit touch surface",
      "In the Box": "HomePod mini, 20W USB-C adapter",
    },
  },
  {
    name: "Amazon Echo Plus (2nd Gen)",
    brand: "Amazon",
    category: "Audio",
    price: 7999,
    mrp: 14999,
    countInStock: 41,
    isFeatured: false,
    images: imgs("amazon-echo-plus"),
    description:
      "Echo Plus has a built-in Zigbee hub, so smart bulbs and plugs connect without a separate bridge. The 3-inch woofer gives it noticeably more low end than the standard Echo.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Amazon warranty",
      "Built-in smart home hub — no bridge needed",
      "7-day easy returns",
    ],
    attributes: { Color: "Charcoal", Power: "Mains powered", Warranty: "1 Year Amazon Warranty" },
    specs: {
      Type: "Smart speaker with hub",
      Audio: "3-inch neodymium woofer, 0.8-inch tweeter",
      "Voice Assistant": "Alexa with seven-microphone array",
      "Smart Home Hub": "Built-in Zigbee hub",
      Connectivity: "Dual-band Wi-Fi, Bluetooth A2DP",
      Sensors: "Built-in temperature sensor",
      Audio_Out: "3.5 mm line out",
      Controls: "Volume ring, mic off button",
      Dimensions: "148 mm high, 99 mm diameter",
      Weight: "780 g",
      "In the Box": "Echo Plus, power adapter, quick start guide",
      Setup: "Alexa app on iOS or Android",
    },
  },

  // ── Watches ──────────────────────────────────────────────────
  {
    name: "Apple Watch Series 4 Gold",
    brand: "Apple",
    category: "Watches",
    price: 26900,
    mrp: 32900,
    countInStock: 31,
    isFeatured: true,
    images: imgs("apple-watch-series-4-gold"),
    description:
      "The Series 4 was the first Apple Watch with an ECG app and fall detection. The edge-to-edge display is 30% larger than the Series 3, and the redesigned Digital Crown adds haptic feedback.",
    benefits: [
      "Free delivery in 2-4 business days",
      "1 year Apple India warranty",
      "ECG and fall detection built in",
      "7-day easy returns",
    ],
    attributes: { Color: "Gold Aluminium", "Case Size": "44 mm", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Display: "LTPO OLED Retina with Force Touch",
      "Case Size": "44 mm",
      "Case Material": "Gold aluminium",
      Processor: "Apple S4 64-bit dual-core",
      Health: "ECG app, optical heart sensor, fall detection",
      Sensors: "Accelerometer, gyroscope, ambient light, barometric altimeter",
      Battery: "Up to 18 hours",
      "Water Resistance": "50 metres (WR50)",
      Connectivity: "Wi-Fi, Bluetooth 5.0, optional LTE",
      Storage: "16 GB",
      Band: "Sport Band included",
      Charging: "Magnetic charging cable",
    },
  },
  {
    name: "Rolex Datejust",
    brand: "Rolex",
    category: "Watches",
    price: 899000,
    mrp: 949000,
    countInStock: 3,
    isFeatured: true,
    images: imgs("rolex-datejust"),
    description:
      "The Datejust has defined the classic wristwatch since 1945 — the first self-winding chronometer to show the date in a window on the dial. Oystersteel case, fluted bezel and the Cyclops lens over the date.",
    benefits: [
      "Free insured delivery with signature on receipt",
      "5 year international manufacturer guarantee",
      "Authenticity certificate included",
      "Complimentary sizing at partner boutiques",
    ],
    attributes: { Color: "Oystersteel / Yellow Gold", "Case Size": "36 mm", Warranty: "5 Year International Guarantee" },
    specs: {
      Movement: "Perpetual, mechanical, self-winding",
      Calibre: "Manufacture Rolex, COSC certified chronometer",
      "Case Size": "36 mm",
      "Case Material": "Oystersteel and yellow gold",
      Bezel: "Fluted, 18 ct yellow gold",
      Crystal: "Scratch-resistant sapphire with Cyclops lens",
      Dial: "Champagne with applied hour markers",
      Bracelet: "Jubilee, five-piece links",
      "Water Resistance": "100 metres (330 ft)",
      "Power Reserve": "Approximately 70 hours",
      Winding: "Bidirectional self-winding via Perpetual rotor",
      Guarantee: "5-year international guarantee",
    },
  },
  {
    name: "Rolex Submariner",
    brand: "Rolex",
    category: "Watches",
    price: 1250000,
    mrp: 1320000,
    countInStock: 2,
    isFeatured: false,
    images: imgs("rolex-submariner-watch"),
    description:
      "The reference diver's watch: waterproof to 300 metres, with a unidirectional rotatable bezel for tracking dive time and Chromalight display that stays legible in total darkness.",
    benefits: [
      "Free insured delivery with signature on receipt",
      "5 year international manufacturer guarantee",
      "Authenticity certificate included",
      "Complimentary sizing at partner boutiques",
    ],
    attributes: { Color: "Oystersteel Black", "Case Size": "41 mm", Warranty: "5 Year International Guarantee" },
    specs: {
      Movement: "Perpetual, mechanical, self-winding",
      Calibre: "Manufacture Rolex, COSC certified chronometer",
      "Case Size": "41 mm",
      "Case Material": "Oystersteel",
      Bezel: "Unidirectional rotatable, 60-minute Cerachrom insert",
      Crystal: "Scratch-resistant sapphire",
      Dial: "Black with Chromalight display",
      Bracelet: "Oyster with Glidelock extension clasp",
      "Water Resistance": "300 metres (1,000 ft)",
      "Power Reserve": "Approximately 70 hours",
      Crown: "Screw-down Triplock triple waterproofness",
      Guarantee: "5-year international guarantee",
    },
  },
  {
    name: "Longines Master Collection",
    brand: "Longines",
    category: "Watches",
    price: 249000,
    mrp: 275000,
    countInStock: 6,
    isFeatured: false,
    images: imgs("longines-master-collection"),
    description:
      "A dress watch in the traditional Swiss idiom — barleycorn guilloche dial, blued steel hands and an exhibition case back that shows off the automatic movement.",
    benefits: [
      "Free insured delivery in 3-5 business days",
      "5 year Longines international warranty",
      "Authenticity certificate included",
      "No Cost EMI from ₹20,750/month",
    ],
    attributes: { Color: "Stainless Steel", "Case Size": "40 mm", Warranty: "5 Year International Warranty" },
    specs: {
      Movement: "Automatic, self-winding",
      Calibre: "Longines exclusive L888",
      "Case Size": "40 mm",
      "Case Material": "Stainless steel",
      Crystal: "Scratch-resistant sapphire with anti-reflective coating",
      Dial: "Silver barleycorn guilloche with blued hands",
      Strap: "Alligator leather with folding clasp",
      "Water Resistance": "30 metres",
      "Power Reserve": "72 hours",
      "Case Back": "Exhibition sapphire case back",
      Functions: "Hours, minutes, seconds, date",
      Guarantee: "5-year international warranty",
    },
  },
  {
    name: "Brown Leather Belt Watch",
    brand: "Fossil",
    category: "Watches",
    price: 6999,
    mrp: 11999,
    countInStock: 54,
    isFeatured: false,
    images: imgs("brown-leather-belt-watch"),
    description:
      "A everyday analogue watch on a genuine leather strap. Clean three-hand dial, mineral glass and a case slim enough to sit comfortably under a shirt cuff.",
    benefits: [
      "Free delivery in 3-5 business days",
      "2 year manufacturer warranty",
      "Pay on delivery available",
      "7-day easy returns",
    ],
    attributes: { Color: "Brown", "Case Size": "42 mm", Warranty: "2 Year Manufacturer Warranty" },
    specs: {
      Movement: "Japanese quartz",
      "Case Size": "42 mm",
      "Case Material": "Stainless steel",
      Crystal: "Mineral glass",
      Dial: "Analogue three-hand with date window",
      Strap: "Genuine leather with buckle closure",
      "Strap Width": "22 mm",
      "Water Resistance": "50 metres (WR50)",
      "Battery Life": "Approximately 2 years",
      "Clasp Type": "Tang buckle",
      Functions: "Hours, minutes, seconds, date",
      Weight: "68 g",
    },
  },

  // ── Accessories ──────────────────────────────────────────────
  {
    name: "Apple MagSafe Battery Pack",
    brand: "Apple",
    category: "Accessories",
    price: 8900,
    mrp: 9900,
    countInStock: 47,
    isFeatured: false,
    images: imgs("apple-magsafe-battery-pack"),
    description:
      "Snaps onto the back of an iPhone magnetically and starts charging — no cable, no case to remove. Plug the pair into a 20W adapter and the iPhone charges at full speed while the pack tops up too.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Apple India warranty",
      "Charges through most MagSafe cases",
      "7-day easy returns",
    ],
    attributes: { Color: "White", Compatibility: "iPhone 12 and later", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Type: "Magnetic wireless power bank",
      Compatibility: "iPhone 12, 13, 14 and 15 series",
      Output: "Up to 15W with 20W adapter attached",
      "Wireless Charging": "5W on the go, 15W when plugged in",
      "Reverse Charging": "Charges over Lightning when connected to power",
      Attachment: "MagSafe magnet array",
      "Battery Status": "Shown on iPhone lock screen and widget",
      "Safety Feature": "Charges to 90% to preserve battery health",
      Charging: "Lightning connector",
      Dimensions: "95.4 x 64 x 11.2 mm",
      Weight: "115 g",
      "In the Box": "MagSafe Battery Pack",
    },
  },
  {
    name: "Apple AirPower Wireless Charger",
    brand: "Apple",
    category: "Accessories",
    price: 3499,
    mrp: 4999,
    countInStock: 58,
    isFeatured: false,
    images: imgs("apple-airpower-wireless-charger"),
    description:
      "A flat Qi charging mat that powers an iPhone, AirPods case or any Qi-compatible device with no alignment fuss. Case-friendly up to 3 mm thickness.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year seller warranty",
      "Works through cases up to 3 mm",
      "7-day easy returns",
    ],
    attributes: { Color: "White", Compatibility: "All Qi devices", Warranty: "1 Year Seller Warranty" },
    specs: {
      Type: "Qi wireless charging mat",
      Output: "Up to 15W",
      Compatibility: "iPhone, AirPods case, Android Qi devices",
      "Case Friendly": "Charges through cases up to 3 mm",
      Input: "USB-C, 9V/2A recommended",
      "Safety Features": "Over-voltage, over-current, foreign object detection",
      Indicator: "LED charging status light",
      Surface: "Non-slip silicone",
      Dimensions: "100 x 100 x 8 mm",
      Weight: "128 g",
      "In the Box": "Charging pad, USB-C cable",
      Note: "Power adapter sold separately",
    },
  },
  {
    name: "Apple 20W USB-C Power Adapter",
    brand: "Apple",
    category: "Accessories",
    price: 1900,
    mrp: 2200,
    countInStock: 120,
    isFeatured: false,
    images: imgs("apple-iphone-charger"),
    description:
      "The compact 20W adapter that fast-charges an iPhone to 50% in around 30 minutes. Also handles iPad, AirPods and Apple Watch charging duties from a single wall socket.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year Apple India warranty",
      "Fast charges iPhone to 50% in 30 minutes",
      "7-day easy returns",
    ],
    attributes: { Color: "White", Output: "20W", Warranty: "1 Year Apple India Warranty" },
    specs: {
      Type: "USB-C power adapter",
      Output: "20W (9V/2.22A or 5V/3A)",
      Connector: "USB-C",
      Compatibility: "iPhone 8 and later, iPad, AirPods, Apple Watch",
      "Fast Charge": "Up to 50% in 30 minutes on iPhone",
      "Input Voltage": "100-240V, 50/60Hz",
      "Protocol": "USB Power Delivery",
      "Plug Type": "Indian 3-pin",
      "Safety Features": "Over-voltage and thermal protection",
      Dimensions: "27 x 27 x 27 mm",
      Weight: "60 g",
      "In the Box": "20W USB-C adapter (cable sold separately)",
    },
  },
  {
    name: "iPhone 12 Silicone Case with MagSafe — Plum",
    brand: "Apple",
    category: "Accessories",
    price: 4500,
    mrp: 4900,
    countInStock: 76,
    isFeatured: false,
    images: imgs("iphone-12-silicone-case-with-magsafe-plum"),
    description:
      "Silky soft-touch silicone over a microfibre lining, with built-in magnets that align perfectly to MagSafe chargers and snap on with a satisfying click.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months warranty against manufacturing defects",
      "Built-in MagSafe magnets",
      "7-day easy returns",
    ],
    attributes: { Color: "Plum", Compatibility: "iPhone 12 / 12 Pro", Warranty: "6 Months Warranty" },
    specs: {
      Type: "Silicone protective case",
      Compatibility: "iPhone 12 and iPhone 12 Pro",
      Material: "Silky soft-touch silicone exterior",
      Lining: "Soft microfibre interior",
      MagSafe: "Built-in magnet array for perfect alignment",
      Buttons: "Machined aluminium, colour-matched",
      Protection: "Raised edges around camera and screen",
      "Wireless Charging": "Supported without removing the case",
      Finish: "Fingerprint resistant",
      Colour: "Plum",
      Weight: "36 g",
      "In the Box": "Silicone case",
    },
  },
  {
    name: "Selfie Stick Monopod with Tripod",
    brand: "Digitek",
    category: "Accessories",
    price: 899,
    mrp: 1499,
    countInStock: 145,
    isFeatured: false,
    images: imgs("selfie-stick-monopod"),
    description:
      "Extends to 1 metre, folds to pocket length and unfolds into a tripod for hands-free shots. The detachable Bluetooth remote works up to 10 metres away.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months warranty",
      "Pay on delivery available",
      "7-day easy returns",
    ],
    attributes: { Color: "Black", "Max Length": "1 metre", Warranty: "6 Months Warranty" },
    specs: {
      Type: "Selfie stick with tripod stand",
      "Maximum Length": "1000 mm",
      "Folded Length": "190 mm",
      "Phone Width": "Fits 55-90 mm devices",
      Remote: "Detachable Bluetooth remote, 10 m range",
      Rotation: "270-degree adjustable head",
      Material: "Aluminium alloy tube, ABS grip",
      "Load Capacity": "Up to 500 g",
      "Battery (remote)": "Rechargeable, 30 hours standby",
      Compatibility: "iOS and Android",
      Weight: "175 g",
      "In the Box": "Selfie stick, Bluetooth remote, USB cable",
    },
  },
  {
    name: "Professional Camera Monopod",
    brand: "Digitek",
    category: "Accessories",
    price: 2499,
    mrp: 3999,
    countInStock: 62,
    isFeatured: false,
    images: imgs("monopod"),
    description:
      "A four-section aluminium monopod for DSLR and mirrorless bodies. Flip locks adjust height in seconds and the foam grip keeps handling steady during long shoots.",
    benefits: [
      "Free delivery in 3-5 business days",
      "1 year warranty",
      "Universal 1/4-inch screw mount",
      "7-day easy returns",
    ],
    attributes: { Color: "Black", "Max Height": "1.6 metres", Warranty: "1 Year Warranty" },
    specs: {
      Type: "Camera monopod",
      Sections: "4-section with flip locks",
      "Maximum Height": "1600 mm",
      "Folded Length": "480 mm",
      "Load Capacity": "Up to 5 kg",
      Mount: "Universal 1/4-inch screw with 3/8-inch adapter",
      Material: "Aluminium alloy",
      Grip: "High-density anti-slip foam",
      "Base Foot": "Rubber with retractable spike",
      Compatibility: "DSLR, mirrorless, camcorders",
      Weight: "480 g",
      "In the Box": "Monopod, carry strap, adapter screw",
    },
  },
  {
    name: "Ring Light with Phone Holder",
    brand: "Digitek",
    category: "Accessories",
    price: 1799,
    mrp: 2999,
    countInStock: 88,
    isFeatured: false,
    images: imgs("selfie-lamp-with-iphone"),
    description:
      "A dimmable LED ring light with three colour temperatures and a clamp that grips any phone. Built for video calls, reels and product shots on a desk.",
    benefits: [
      "Free delivery in 3-5 business days",
      "6 months warranty",
      "USB powered — works with any power bank",
      "7-day easy returns",
    ],
    attributes: { Color: "Black", Power: "USB powered", Warranty: "6 Months Warranty" },
    specs: {
      Type: "LED ring light with phone clamp",
      "Ring Diameter": "260 mm",
      "Colour Temperatures": "Warm 3000K, Natural 4500K, Cool 6000K",
      Brightness: "10 dimmable levels per mode",
      "LED Count": "120 SMD LEDs",
      Power: "USB 5V, works with power banks",
      Mount: "Adjustable clamp, fits 55-90 mm phones",
      "Stand Height": "Adjustable 500-1600 mm",
      Rotation: "360-degree ball head",
      "Cable Length": "1.8 m USB",
      Weight: "620 g with stand",
      "In the Box": "Ring light, tripod stand, phone holder, USB cable",
    },
  },
  {
    name: "Studio Camera Pedestal Stand",
    brand: "Digitek",
    category: "Accessories",
    price: 18999,
    mrp: 27999,
    countInStock: 9,
    isFeatured: false,
    images: imgs("tv-studio-camera-pedestal"),
    description:
      "A broadcast-grade pedestal with a pneumatic column and locking castors. Designed for studio cameras where smooth, repeatable height changes matter more than portability.",
    benefits: [
      "Free delivery in 5-7 business days",
      "1 year warranty with onsite support",
      "Assembly guidance included",
      "7-day replacement on defects",
    ],
    attributes: { Color: "Black", "Max Height": "1.5 metres", Warranty: "1 Year Onsite Warranty" },
    specs: {
      Type: "Studio camera pedestal",
      "Column Type": "Pneumatic assisted",
      "Height Range": "700-1500 mm",
      "Load Capacity": "Up to 25 kg",
      Base: "Three-castor dolly with individual locks",
      "Castor Diameter": "100 mm",
      Mount: "Flat top with 1/4-inch and 3/8-inch threads",
      Levelling: "Built-in bubble level",
      Material: "Powder-coated steel and aluminium",
      "Steering Modes": "Tricycle and crab steering",
      Weight: "22 kg",
      "In the Box": "Pedestal, dolly base, mounting hardware",
    },
  },
];

// ─────────────────────────────────────────────────────────────────────────
// Variants
// ─────────────────────────────────────────────────────────────────────────
//
// Each product sells in 2-5 real configurations. A variant carries its own
// price and stock, so picking "256 GB" on the product page genuinely changes
// what the shopper pays and what gets reserved from inventory.
//
// Entries are [attributes, price, countInStock]. The first variant of each
// product is the default and always matches the product's own base price.

const V = (rows) =>
  rows.map(([attributes, price, countInStock]) => ({ attributes, price, countInStock }));

export const variantsByProduct = {
  // ── Smartphones: storage tiers + colour ──────────────────────
  "Apple iPhone 13 Pro": V([
    [{ Storage: "128 GB", Color: "Sierra Blue" }, 89900, 12],
    [{ Storage: "256 GB", Color: "Sierra Blue" }, 99900, 9],
    [{ Storage: "256 GB", Color: "Graphite" }, 99900, 7],
    [{ Storage: "512 GB", Color: "Graphite" }, 119900, 6],
  ]),
  "Apple iPhone X": V([
    [{ Storage: "64 GB", Color: "Space Grey" }, 34999, 11],
    [{ Storage: "64 GB", Color: "Silver" }, 34999, 6],
    [{ Storage: "256 GB", Color: "Space Grey" }, 41999, 4],
  ]),
  "Samsung Galaxy S10": V([
    [{ Storage: "128 GB", Color: "Prism White" }, 38999, 16],
    [{ Storage: "128 GB", Color: "Prism Black" }, 38999, 12],
    [{ Storage: "512 GB", Color: "Prism White" }, 47999, 7],
    [{ Storage: "512 GB", Color: "Prism Blue" }, 47999, 5],
  ]),
  "Samsung Galaxy S8": V([
    [{ Storage: "64 GB", Color: "Midnight Black" }, 21999, 14],
    [{ Storage: "64 GB", Color: "Orchid Grey" }, 21999, 8],
    [{ Storage: "128 GB", Color: "Midnight Black" }, 25999, 4],
  ]),
  "OPPO F19 Pro+ 5G": V([
    [{ Storage: "128 GB", RAM: "8 GB", Color: "Fluid Black" }, 22990, 22],
    [{ Storage: "128 GB", RAM: "8 GB", Color: "Space Silver" }, 22990, 18],
    [{ Storage: "256 GB", RAM: "8 GB", Color: "Fluid Black" }, 25990, 12],
  ]),
  "OPPO K1": V([
    [{ Storage: "64 GB", RAM: "4 GB", Color: "Astral Blue" }, 13990, 30],
    [{ Storage: "64 GB", RAM: "6 GB", Color: "Astral Blue" }, 15490, 21],
    [{ Storage: "128 GB", RAM: "6 GB", Color: "Piano Black" }, 17490, 12],
  ]),
  "Realme XT": V([
    [{ Storage: "128 GB", RAM: "8 GB", Color: "Pearl Blue" }, 15999, 20],
    [{ Storage: "128 GB", RAM: "8 GB", Color: "Pearl White" }, 15999, 16],
    [{ Storage: "64 GB", RAM: "4 GB", Color: "Pearl Blue" }, 13999, 12],
  ]),
  "Vivo X21": V([
    [{ Storage: "128 GB", RAM: "6 GB", Color: "Ruby Red" }, 17990, 14],
    [{ Storage: "128 GB", RAM: "6 GB", Color: "Black" }, 17990, 10],
    [{ Storage: "256 GB", RAM: "8 GB", Color: "Black" }, 21990, 6],
  ]),

  // ── Laptops: RAM + SSD configurations ────────────────────────
  'Apple MacBook Pro 14" Space Grey': V([
    [{ RAM: "16 GB", Storage: "512 GB SSD" }, 169900, 8],
    [{ RAM: "16 GB", Storage: "1 TB SSD" }, 189900, 5],
    [{ RAM: "32 GB", Storage: "1 TB SSD" }, 229900, 3],
    [{ RAM: "32 GB", Storage: "2 TB SSD" }, 269900, 2],
  ]),
  "ASUS Zenbook Pro Duo": V([
    [{ RAM: "16 GB", Storage: "1 TB SSD" }, 149990, 6],
    [{ RAM: "32 GB", Storage: "1 TB SSD" }, 169990, 4],
    [{ RAM: "32 GB", Storage: "2 TB SSD" }, 189990, 2],
  ]),
  "Huawei MateBook X Pro": V([
    [{ RAM: "16 GB", Storage: "512 GB SSD" }, 109990, 8],
    [{ RAM: "16 GB", Storage: "1 TB SSD" }, 119990, 5],
    [{ RAM: "16 GB", Storage: "1 TB SSD", Color: "Ink Blue" }, 122990, 2],
  ]),
  "Lenovo Yoga 920 2-in-1": V([
    [{ RAM: "8 GB", Storage: "512 GB SSD" }, 84990, 11],
    [{ RAM: "16 GB", Storage: "512 GB SSD" }, 94990, 6],
    [{ RAM: "16 GB", Storage: "1 TB SSD" }, 104990, 3],
  ]),
  "Dell XPS 13 9300": V([
    [{ RAM: "16 GB", Storage: "512 GB SSD" }, 99990, 12],
    [{ RAM: "16 GB", Storage: "1 TB SSD" }, 114990, 7],
    [{ RAM: "32 GB", Storage: "1 TB SSD" }, 134990, 5],
  ]),

  // ── Tablets: storage + connectivity ──────────────────────────
  "Apple iPad Mini (2021) Starlight": V([
    [{ Storage: "64 GB", Connectivity: "Wi-Fi" }, 49900, 14],
    [{ Storage: "256 GB", Connectivity: "Wi-Fi" }, 64900, 9],
    [{ Storage: "64 GB", Connectivity: "Wi-Fi + Cellular" }, 64900, 4],
    [{ Storage: "256 GB", Connectivity: "Wi-Fi + Cellular" }, 79900, 2],
  ]),
  "Samsung Galaxy Tab S8+ Grey": V([
    [{ Storage: "128 GB", Connectivity: "Wi-Fi" }, 74999, 10],
    [{ Storage: "256 GB", Connectivity: "Wi-Fi" }, 84999, 7],
    [{ Storage: "256 GB", Connectivity: "Wi-Fi + 5G" }, 99999, 5],
  ]),
  "Samsung Galaxy Tab A White": V([
    [{ Storage: "64 GB", Connectivity: "Wi-Fi" }, 18999, 25],
    [{ Storage: "128 GB", Connectivity: "Wi-Fi" }, 21999, 14],
    [{ Storage: "64 GB", Connectivity: "Wi-Fi + LTE" }, 23999, 6],
  ]),

  // ── Audio ────────────────────────────────────────────────────
  "Apple AirPods (3rd Generation)": V([
    [{ "Charging Case": "MagSafe" }, 18900, 40],
    [{ "Charging Case": "Lightning" }, 16900, 28],
  ]),
  "Apple AirPods Max Silver": V([
    [{ Color: "Silver" }, 59900, 6],
    [{ Color: "Space Grey" }, 59900, 4],
    [{ Color: "Sky Blue" }, 59900, 2],
    [{ Color: "Green" }, 59900, 2],
  ]),
  "Beats Flex Wireless Earphones": V([
    [{ Color: "Beats Black" }, 4999, 38],
    [{ Color: "Yuzu Yellow" }, 4999, 30],
    [{ Color: "Flame Blue" }, 4999, 24],
  ]),
  "Apple HomePod Mini Cosmic Grey": V([
    [{ Color: "Cosmic Grey" }, 10900, 18],
    [{ Color: "White" }, 10900, 12],
    [{ Color: "Blue" }, 11400, 7],
  ]),
  "Amazon Echo Plus (2nd Gen)": V([
    [{ Color: "Charcoal" }, 7999, 20],
    [{ Color: "Sandstone" }, 7999, 13],
    [{ Color: "Heather Grey" }, 8499, 8],
  ]),

  // ── Watches ──────────────────────────────────────────────────
  "Apple Watch Series 4 Gold": V([
    [{ "Case Size": "40 mm", Connectivity: "GPS" }, 24900, 13],
    [{ "Case Size": "44 mm", Connectivity: "GPS" }, 26900, 10],
    [{ "Case Size": "40 mm", Connectivity: "GPS + Cellular" }, 30900, 5],
    [{ "Case Size": "44 mm", Connectivity: "GPS + Cellular" }, 32900, 3],
  ]),
  "Rolex Datejust": V([
    [{ "Case Size": "36 mm", Bracelet: "Jubilee" }, 899000, 2],
    [{ "Case Size": "41 mm", Bracelet: "Jubilee" }, 949000, 1],
  ]),
  "Rolex Submariner": V([
    [{ "Case Size": "41 mm", Dial: "Black" }, 1250000, 1],
    [{ "Case Size": "41 mm", Dial: "Green" }, 1320000, 1],
  ]),
  "Longines Master Collection": V([
    [{ "Case Size": "40 mm", Strap: "Alligator Leather" }, 249000, 3],
    [{ "Case Size": "40 mm", Strap: "Stainless Steel" }, 259000, 2],
    [{ "Case Size": "42 mm", Strap: "Alligator Leather" }, 265000, 1],
  ]),
  "Brown Leather Belt Watch": V([
    [{ Color: "Brown", "Strap Width": "22 mm" }, 6999, 24],
    [{ Color: "Black", "Strap Width": "22 mm" }, 6999, 18],
    [{ Color: "Tan", "Strap Width": "20 mm" }, 7499, 12],
  ]),

  // ── Accessories ──────────────────────────────────────────────
  "Apple MagSafe Battery Pack": V([
    [{ Color: "White" }, 8900, 30],
    [{ Color: "White", Bundle: "With 20W Adapter" }, 10400, 17],
  ]),
  "Apple AirPower Wireless Charger": V([
    [{ Color: "White", Output: "15W" }, 3499, 34],
    [{ Color: "Black", Output: "15W" }, 3499, 24],
  ]),
  "Apple 20W USB-C Power Adapter": V([
    [{ Bundle: "Adapter only" }, 1900, 70],
    [{ Bundle: "With USB-C to Lightning cable" }, 3400, 50],
  ]),
  "iPhone 12 Silicone Case with MagSafe — Plum": V([
    [{ Color: "Plum" }, 4500, 30],
    [{ Color: "Deep Navy" }, 4500, 26],
    [{ Color: "Pink Citrus" }, 4500, 20],
  ]),
  "Selfie Stick Monopod with Tripod": V([
    [{ Color: "Black" }, 899, 90],
    [{ Color: "Rose Gold" }, 999, 55],
  ]),
  "Professional Camera Monopod": V([
    [{ "Max Height": "1.6 m" }, 2499, 40],
    [{ "Max Height": "2.0 m" }, 3299, 22],
  ]),
  "Ring Light with Phone Holder": V([
    [{ "Ring Diameter": "26 cm" }, 1799, 50],
    [{ "Ring Diameter": "33 cm" }, 2599, 24],
    [{ "Ring Diameter": "45 cm" }, 3999, 14],
  ]),
  "Studio Camera Pedestal Stand": V([
    [{ "Load Capacity": "25 kg" }, 18999, 6],
    [{ "Load Capacity": "40 kg" }, 26999, 3],
  ]),
};

export default catalogue;
